### PR TITLE
Generate raster tiles with Mercantile and Pillow

### PR DESCRIPTION
**Pull request by kgraaf**
This PR generates raster tiles with Mercantile and Pillow instead of Pingrid. Right now the images are in black and white, I'll need to add the colormap.

Working sample URL http://127.0.0.1:8050/onset-maproom-tiles/onset/7/78/60/1/5/20/3/7/21 (adjust host name and port accordingly of course)

### CODE REVIEW

**Comment by kgraaf** [comment]
Currently this is very slow (approximately 30 sec per tile). However, I have not tested it with rechunked data yet.

**Review by aaron-kaplan — COMMENTED** [review]
[Edit: some of this is wrong. See later comment.]

A square tile in Mercator space corresponds to a non-rectangular region in the equirectangular projection. Instead of finding that non-rectangular region, you're finding its rectangular bounding box, fetching the data for that bounding box, and then calling `resize` on it to squash it into a square. That might look ok superficially, in the sense that pixels appear on the part of the map where we expect to see pixels, but it's not the right pixels.

Since Ethiopia is close to the equator, where the Mercator projection isn't very different from the equirectangular, it might actually be good enough, but if you tried it on Norway I don't think it would be close.

Rather than mapping the entire tile to equirectangular space, pingrid.py:produce_data_tile maps each pixel of the Mercator tile to the centroid of its projection into equirectangular space, and then interpolates to get values at those points.

A week ago I'm not sure I would have understood that what you're doing is wrong, or at least it would have taken me a lot longer. What changed since then is that I spent hours this week reading pingrid.py and cross-checking with the wikipedia page and some other resources on the Mercator projection. It was very educational.

BTW I'm doing a similar experiment on the fbfmaproom but with matplotlib, which has map projection functions, instead of pillow. fbfmaproom is a better place for this kind of experiment because there's no expensive calculation involved, it's just loading data from disk and displaying it.

**Comment by aaron-kaplan** [comment]
I think this shows that there are good prospects for replacing much of pingrid with existing libraries, but that's not what we're working on right now. Since we managed to encapsulate all the cv2 stuff, we can go ahead and use it for now without tying ourselves to it forever. There are other demands that are more pressing.

**Comment by aaron-kaplan** [comment]
Part of my earlier comment was wrong. A square in Mercator space projects to a rectangle in equirectangular space. The problem is just that `resize` will stretch all the pixels equally, when in fact the projection back into Mercator should stretch pixels at the north end more than those at the south end. (Right?)

**Comment by remicousin** [comment]
I would need to do some research on the 2 projections and resize to try and answer that question, is that is what you seek. let me know

**Comment by aaron-kaplan** [comment]
@remicousin don't put any time into it, at least for now. I think our preferred solution is to switch to the equirectangular projection, like Ingrid, which would make this point moot. It remains to be seen how difficult that will be.

**Pull request closed without merging**
