### PR TITLE
Remic/species

### PR DESCRIPTION
**Pull request by remicousin**
Main objective was to add the multiple species data in the app. Was so far reading data for 1 species (1 files). In the process:

- read and appended multiple species files;
- dropped error variable (reading, drop-down menu, mapping and ts) per data provider request;
- indexing by city/town/country is done during reading;
- Species dropdown updates both map and ts;
- Revisited ts title;
- simpler constant colorscale to facilitate comparisons through species/weeks
- text updates to talk about species
- text revisiting for other cosmetics and such

### CODE REVIEW

**Comment by drewmresnick** [comment]
When I try to run it I get an error, and the species dropdown does not have any options. 

running as CONFIG=config-sample.yaml python diversity_maproom.py

error message (not a very helpful one at that..):


`Invalid argument options[0].label passed into Dropdown with ID "species_dropdown"`.

`(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)`
`
propTypeErrorHandler@webpack://dash_renderer/./src/exceptions.js?:116:9`

`CheckedComponent@webpack://dash_renderer/./src/TreeContainer.js?:97:70`

`renderWithHooks@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:14938:29`

`mountIndeterminateComponent@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:17617:15`

`beginWork@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:18731:18`

`callCallback@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:182:16`

`invokeGuardedCallbackDev@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:231:18`

`invokeGuardedCallback@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:286:33`

`beginWork$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:23338:30`

`performUnitOfWork@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:22292:14`

`workLoopSync@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:22265:24`

`performSyncWorkOnRoot@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:21891:11`

`flushSyncCallbackQueueImpl/<@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:11224:26`
`
unstable_runWithPriority@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v1_21_0m1627189189.14.0.js:2685:14`

`runWithPriority$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:11174:12`
`
flushSyncCallbackQueueImpl@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:11219:26`

`flushSyncCallbackQueue@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:11207:5`

`flushPassiveEffectsImpl@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:23018:5`

`unstable_runWithPriority@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v1_21_0m1627189189.14.0.js:2685:14`
`
runWithPriority$1@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:11174:12`

`flushPassiveEffects@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:22955:14`

`commitBeforeMutationEffects/<@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v1_21_0m1627189189.14.0.js:22834:13`

`workLoop@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v1_21_0m1627189189.14.0.js:2629:44`

`flushWork@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v1_21_0m1627189189.14.0.js:2584:18`

`performWorkUntilDeadline@http://127.0.0.1:8050/_dash-component-suites/dash/deps/react@16.v1_21_0m1627189189.14.0.js:2196:50`

**Comment by aaron-kaplan** [comment]
Invalid argument options[0].label passed into Dropdown with ID
"species_dropdown".
Seems like the relevant part of the error message.

**Comment by remicousin** [comment]
hmmm... I don't understand: I have no error message, a populated species dropdown and the rest of the DashRoom reponds to it...

BTY, I was thinking we could call these MAppRooms...

**Comment by drewmresnick** [comment]
That is strange, I am not sure how that would be possible but I tried in firefox and chrome and get the same error in both

**Comment by remicousin** [comment]
[0] of this dropdown is disabled and just here for cosmetics. Default is set up at [1]. So I am not sure how your system finds a way to select [0].
I can comment out the disabled options that are here for cosmetics that are possibly why causes trouble.
Even though unclear...

**Comment by drewmresnick** [comment]
Ah yes if I comment out those in the list that have disabled set to true then it works for me. Not sure why there is an inconsistency there in how it is working for the both of us though.

**Comment by remicousin** [comment]
is it possible that you had option [0] "saved" in some sort of a cache or something?

**Comment by drewmresnick** [comment]
hmm. not entirely sure about that one..

**Comment by drewmresnick** [comment]
This works properly for me now. The only thing is that the title for the time series plot updates using the species ID, which does not seem very descriptive. Perhaps we can merge this branch and then you can work on fixing that on a few branch for improving cosmetics @remicousin ?

**Comment by remicousin** [comment]
Yes. I tried to pass on the label rather than the value, or both, but that didn't go very well, so I cut short.

**Comment by drewmresnick** [comment]
Ah I see. For now that will do and maybe we can think of a better title for the plot

**Review by drewmresnick — APPROVED** [review]

**Comment by remicousin** [comment]
@aaron-kaplan , would you like to do a quick review? we are a bit in a rush to get a mvp by tomorrow afternoon when the poster is presented. There are still the addition of outage data and some text cleaning that are missing. So I guess we are looking for red flags right now and if not, merge so that we can get there and return to improvements once the talk is given.

**Review by aaron-kaplan — APPROVED** [review]
Nothing jumps out at me. We really need some tests, but that'll take some time to set up.

**Pull request merged**
