### PR TITLE
handle condition where no data exists for current location

### PR DESCRIPTION
**Pull request by kgraaf**
Ensures that the table will not show erroneous data

### CODE REVIEW

**Review by aaron-kaplan — CHANGES_REQUESTED** [review]
Same comment as on the other PR: use `except Exception` instead of just `except`, and when there's no data add a message explaining why.

**Comment by kgraaf** [comment]
If you want text to be overlayed on the map, there is already a tool tip that says "no data" when you drag the marker to a location without data. I think that would be redundant to also have an overlay

**Comment by aaron-kaplan** [comment]
Oh yeah, so there is. Please remove the message then, and put back the `width: 1px`, which is there for a reason.

**Comment by kgraaf** [comment]
This should be ready to go

**Review by aaron-kaplan — APPROVED** [review]
Looks good. We need to bump the version number in __about__.py before releasing. If the other PR is about to get merged then you can merge this as-is, bump the version in the other one, and then release.

**Pull request merged**
